### PR TITLE
fix rollupDB-levelDB chainID, remove exit-tree, add exitBalance & accumulatedHash

### LINKED ISSUE #26: remove exit-tree
Please, check new specification in the following [link](https://github.com/hermeznetwork/docs/blob/feature/update-v1/docs/developers/protocol/hermez-protocol/protocol.md)
Also, check circuit issue regarding this topic [here](https://github.com/hermeznetwork/circuits/issues/38)

## Overview changes
- update `state-utils.js`: add new fields `exitBalance` and `accumulateHash`
- update `batch-builder.js`: remove exit-tree. Add logic to add exits to `exitBalance` and compute `accumulatedHash`
- update `rollupDB.js`: remove storage exit-tree, ability to retrieve new exit information

### PR DESCRIPTION
**Pull request by krlosMata**
This PR does the following:
- fix loading rollupDB from LevelDB
- removes exit-tree
- adds `exitBalance` & `accumulatedHash` in state-tree leafs
- updates `zkInputs` to match new protocol

Please, refer to the follwoing specification for more details: https://github.com/hermeznetwork/docs/blob/feature/update-v1/docs/developers/protocol/hermez-protocol/protocol.md

close #26

### CODE REVIEW

File: src/batch-builder.js [hunk 1]
```diff
@@ -394,37 +381,44 @@ module.exports = class BatchBuilder {
...
             newState2 = Object.assign({}, oldState2);
-            newState2.balance = Scalar.add(oldState2.balance, effectiveAmount);
-        }
 
-        if (op1=="INSERT") {
+            if (isExit){
+                newState2.exitBalance = Scalar.add(oldState2.exitBalance, effectiveAmount);
+            } else {
+                newState2.balance = Scalar.add(oldState2.balance, effectiveAmount);
+                newState2.accumulatedHash = stateUtils.computeAccumulatedHash(oldState2.accumulatedHash, tx, this.nLevels);
```
Comment (jesusholoo) [inline src/batch-builder.js:395]: Accumulate hash should take in account if the amount is or not nullified in case of L1!

File: src/batch-builder.js [hunk 2]
```diff
@@ -567,148 +563,68 @@ module.exports = class BatchBuilder {
...
+        } else {
+            updateToIdx = finalToIdx;
+        }
 
-                this.input.newExit[i] = 1;   // must be 1 to signal new exit leaf
-                this.input.siblings2[i] = siblings;
-                this.input.isOld0_2[i] = res.isOld0 ? 1 : 0;
-                this.input.oldKey2[i] = res.isOld0 ? 0 : res.oldKey;
-                this.input.oldValue2[i] = res.isOld0 ? 0 : res.oldValue;
+        if (op2 == "UPDATE") {
```
Comment (jesusholoo) [inline src/batch-builder.js:573]: Exit operation could be performed in OP1 since are changes in the same leaf. Could this be more efficient?

File: src/batch-builder.js (hunk 1 above)
Comment (krlosMata) [reply src/batch-builder.js:395]: good catch !

File: src/batch-builder.js (hunk 2 above)
Comment (krlosMata) [reply src/batch-builder.js:573]: Yes, it could be done in such a way. However, this it does not provide more efficiency in terms of constraints since `processor2` should be added in all transactions in the circuit in order to perform standard transfers. Therefore, the number of constraints would be the same.
Said that, both approaches are totally valid in exits, either update both balances in `processor1` or just update `balance` in `processor1` and `exitBalance` in `processor2`. I took the second approach since it is more similar to the one that we have previously.

**Review by laisolizq — APPROVED** [review]
:smile_cat: :top: !!

**Review by jesusholoo — APPROVED** [review]
nice :D
